### ISSUE TITLE
‘#Tag’, text with ‘#’ will be striped, using IFTTT

### ISSUE THREAD

**Issue by bleedingsaber** [mlava/json-webhooks#5]
Hi, try to send a roam block to other note app, if the block text includes a tag '#iamatag', the tag '#iamatag' will be striped. I am using IFTTT, does this cause by IFTTT?

**Comment by bleedingsaber** [comment]
Pipedream is working properly, I think this is caused by IFTTT.

**Comment by bleedingsaber** [comment]
Could we allow to add a specific tag after running the webhook, notifying me this block already has been handled.

**Comment by mlava** [comment]
@bleedingsaber 
Sorry for the long delay in responding to you.
I have implemented the confirmation in https://github.com/Roam-Research/roam-depot/pull/857
You just need to wait for the RR team to review and approve.
Cheers!

**Comment by mlava** [comment]
This PR has been approved and the new version is available. Cheers!
