### ISSUE TITLE
Add success Indicator for each webhook export

### ISSUE THREAD

**Issue by frankamedic** [mlava/json-webhooks#7]
This request is to add a configurable status string/emoji for each webhook.

When export succeeds, append this string to the focused block as a basic indication that the block had been exported. 

Settings should probably be a checkbox to enable for each webhook endpoint, and a field for the user can set each string. 

After sending, string gets appended to the line the cursor was on.

**Comment by mlava** [comment]
Hi @frankamedic 
This is implemented in https://github.com/Roam-Research/roam-depot/pull/857
You just need to wait for the RR team to review and approve.
Cheers!

**Comment by mlava** [comment]
This PR has been approved and the new version is available. Cheers!
