### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by tombarys** [mlava/json-webhooks#8]
Hi, Mark, this is probably not too much related to this extension but I have the question: is possible to use this extension (or create a new one) to automatically send some kind of notifications when some particular condition regarding graph content is met? Would be especially useful in shared graphs.

The simplest: someone creates a block containing a specific keyword (or tag). 

Question: would it require standalone server to regularly check for changes? (probably yes, anyone could easily setup one somewhere, or not?)

Thanks for your extensions and your time!
Tomáš

**Comment by mlava** [comment]
Hi Tomáš,
I think you could do it with pullwatch https://roamresearch.com/#/app/developer-documentation/page/mOlEL9nkU see addPullWatch and removePullWatch.
My Unread Notification extension is a simple example of how to use (https://github.com/mlava/unread-badge/blob/main/extension.js#L297)... Let me know how you go!

**Comment by tombarys** [comment]
Oh, great, I completely missed it. Thanks, Mark.
